# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puntaje_juego',
            fields=[
                ('valor', models.IntegerField()),
                ('id_puntaje', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
    ]
