# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puntaje_juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador_VideoJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntaje_juegos.Videojuego')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Puntaje_juego',
        ),
    ]
